---
- name: Flannel | Create Flannel manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/{{ item.file }}"
  with_items:
    - {name: flannel, file: cni-flannel-rbac.yml, type: sa}
    - {name: kube-flannel, file: cni-flannel.yml, type: ds}
  register: flannel_node_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Flannel | Create Flannel manifests for arm64 nodes
  include: cni-flannel-arm64.yml
  when:
    - ansible_architecture == "aarch64"

